import { Role, Users, UserStatus } from "@/__generated__/graphql";

export const dummyEmployeeData: Users[] = [
  {
    id: "1",
    Fname: "Jackson",
    Sname: "Smith",
    email: "jackson.smith@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Offline,
    phone: "+1 555-123-4567",
    image: "https://randomuser.me/api/portraits/men/32.jpg",
    businessId: 1,
  },
  {
    id: "2",
    Fname: "Alice",
    Sname: "Johnson",
    email: "alice.johnson@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Idle,
    phone: "+1 555-234-5678",
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    businessId: 1,
  },
  {
    id: "3",
    Fname: "Peter",
    Sname: "Williams",
    email: "peter.williams@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Active,
    phone: "+1 555-345-6789",
    image: "https://randomuser.me/api/portraits/men/57.jpg",
    businessId: 2,
  },
  {
    id: "4",
    Fname: "Joan",
    Sname: "Brown",
    email: "joan.brown@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Active,
    phone: "+1 555-456-7890",
    image: "https://randomuser.me/api/portraits/women/22.jpg",
    businessId: 1,
  },
  {
    id: "5",
    Fname: "Francis",
    Sname: "Jones",
    email: "francis.jones@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Offline,
    phone: "+1 555-567-8901",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
    businessId: 2,
  },
  {
    id: "6",
    Fname: "Lucy",
    Sname: "Garcia",
    email: "lucy.garcia@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-15T14:30:00"),
    status: UserStatus.Active,
    phone: "+1 555-678-9012",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    businessId: 1,
  },
  {
    id: "7",
    Fname: "Michael",
    Sname: "Davis",
    email: "michael.davis@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-14T09:45:00"),
    status: UserStatus.Active,
    phone: "+1 555-789-0123",
    image: "https://randomuser.me/api/portraits/men/42.jpg",
    businessId: 1,
  },
  {
    id: "8",
    Fname: "Sarah",
    Sname: "Wilson",
    email: "sarah.wilson@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-14T16:20:00"),
    status: UserStatus.Idle,
    phone: "+1 555-890-1234",
    image: "https://randomuser.me/api/portraits/women/33.jpg",
    businessId: 2,
  },
  {
    id: "9",
    Fname: "David",
    Sname: "Taylor",
    email: "david.taylor@flowbiz.com",
    role: Role.Admin,
    lastLogin: new Date("2023-09-15T08:15:00"),
    status: UserStatus.Active,
    phone: "+1 555-901-2345",
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    businessId: 1,
  },
  {
    id: "10",
    Fname: "Emma",
    Sname: "Martinez",
    email: "emma.martinez@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-13T14:30:00"),
    status: UserStatus.Offline,
    phone: "+1 555-012-3456",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
    businessId: 2,
  },
  {
    id: "11",
    Fname: "James",
    Sname: "Anderson",
    email: "james.anderson@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-14T11:20:00"),
    status: UserStatus.Active,
    phone: "+1 555-123-7890",
    image: "https://randomuser.me/api/portraits/men/67.jpg",
    businessId: 1,
  },
  {
    id: "12",
    Fname: "Olivia",
    Sname: "Thomas",
    email: "olivia.thomas@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-15T10:45:00"),
    status: UserStatus.Idle,
    phone: "+1 555-234-8901",
    image: "https://randomuser.me/api/portraits/women/52.jpg",
    businessId: 2,
  },
  {
    id: "13",
    Fname: "William",
    Sname: "Jackson",
    email: "william.jackson@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-13T16:50:00"),
    status: UserStatus.Active,
    phone: "+1 555-345-9012",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
    businessId: 1,
  },
  {
    id: "14",
    Fname: "Sophia",
    Sname: "White",
    email: "sophia.white@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-14T13:15:00"),
    status: UserStatus.Offline,
    phone: "+1 555-456-0123",
    image: "https://randomuser.me/api/portraits/women/89.jpg",
    businessId: 2,
  },
  {
    id: "15",
    Fname: "Benjamin",
    Sname: "Harris",
    email: "benjamin.harris@flowbiz.com",
    role: Role.Admin,
    lastLogin: new Date("2023-09-15T09:30:00"),
    status: UserStatus.Active,
    phone: "+1 555-567-1234",
    image: "https://randomuser.me/api/portraits/men/91.jpg",
    businessId: 1,
  },
  {
    id: "16",
    Fname: "Isabella",
    Sname: "Martin",
    email: "isabella.martin@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-14T14:40:00"),
    status: UserStatus.Idle,
    phone: "+1 555-678-2345",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
    businessId: 2,
  },
  {
    id: "17",
    Fname: "Henry",
    Sname: "Thompson",
    email: "henry.thompson@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-13T10:25:00"),
    status: UserStatus.Active,
    phone: "+1 555-789-3456",
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    businessId: 1,
  },
  {
    id: "18",
    Fname: "Ava",
    Sname: "Garcia",
    email: "ava.garcia@flowbiz.com",
    role: Role.MarketingRep,
    lastLogin: new Date("2023-09-15T11:55:00"),
    status: UserStatus.Offline,
    phone: "+1 555-890-4567",
    image: "https://randomuser.me/api/portraits/women/62.jpg",
    businessId: 2,
  },
  {
    id: "19",
    Fname: "Alexander",
    Sname: "Martinez",
    email: "alexander.martinez@flowbiz.com",
    role: Role.SalesRep,
    lastLogin: new Date("2023-09-14T15:10:00"),
    status: UserStatus.Active,
    phone: "+1 555-901-5678",
    image: "https://randomuser.me/api/portraits/men/39.jpg",
    businessId: 1,
  },
];
